### PR TITLE
Fix initial code py3

### PR DESCRIPTION
**Pull request by cielavenir**
Could you fix Py2 too?

### CODE REVIEW

**Comment by cielavenir** [comment]
Sorry for buggy branch name (caused by misedit)

**Comment by cielavenir** [comment]
Aww...
https://github.com/Bryukh-Checkio-Tasks/checkio-mission-network-loops/blob/master/verification/referee.py has cover code, but it is not used...

Looks like current fix for initial_code is not good. Perhaps I should make another pull-req?
(Thanks @Sim00)

**Comment by cielavenir** [comment]
Or if initial_code is correct, you should make

``` py
cover_code={
            'python-27': cover,
            'python-3': cover
        },
```

**Comment by Bryukh** [comment]
Yeah, you are right. Fixed

**Comment by cielavenir** [comment]
[edit] https://github.com/Bryukh-Checkio-Tasks/checkio-mission-network-loops/blob/master/verification/referee.py#L56 is ok with [n1, n2] (list) because data is not affected by cover().

**Comment by Bryukh** [comment]
Nope, it's not the same. The checker receive list from tests, because them pass through json. but not through cover.

**Comment by cielavenir** [comment]
Your reply was faster than my edit :)

**Comment by Bryukh** [comment]
Oh, got it :-) I read your comment in email and answer without rereading edited version.

**Pull request merged**
